package com.demo.EmployeeDb.dto;

// DTO for sending department data in responses
// Entity never exposed outside the service layer
public class DepartmentResponseDto {

    // Department ID generated by the database
    private Long id;

    // Name of the department
    private String name;

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
}